name: oldOPGapRecipe
version: '1.0'
main: com.jotrorox.oldOPGapRecipe.OldOPGapRecipe
api-version: '1.21'
author: Jotrorox
description: A plugin that adds the old OP golden apple recipe back to the game.
